In [5]:
import numpy as np
#question 1: write python code to produce the following output using numpy:


my array is: 
[[ 7  8  9]
 [10 11 12]]
my array shape is:  (2, 3)


In [3]:
#question 1: your answer goes here..
import numpy as np
arr = np.array([[7,8,9], [10,11,12]])
print("my array is: ")
print (arr)
print("my array shape is:  ",arr.shape)

my array is: 
[[ 7  8  9]
 [10 11 12]]
my array shape is:   (2, 3)


In [ ]:
#question 1 answer: 
m=np.array([[7,8,9], [10,11,12]])
print("my array is: ")
print(m)
print("my array shape is: ",m.shape)

In [6]:
#question 2: produce the following output: 


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [7]:
#question 2: your answer goes here..
n=np.arange(0,30,2)
n
o=n.reshape(3,5)
o

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
#question 2 answer: 
n=np.arange(0,30,2)
n
o=n.reshape(3,5)
o

In [7]:
#question 3: write python code to display 9 numbers from 0 to 4 with an equal step size
#to produce the following output: 




array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [8]:
#question 3: your answer goes here..
o=np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
#question 3 answer: 
o=np.linspace(0,4,9)
o

In [8]:
#question 4: write python code to produce the following output in 2 lines of code: 


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [9]:
#question 4: your answer goes here..
mylist=[1,2,3]
np.diag(mylist)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
#question 4 answer: 
mylist=[1,2,3]
np.diag(mylist)

In [9]:
#question 5: write python code to display the following output in 2 lines of code: 



array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [10]:
#question 5: your answer goes here..
p=np.ones([2,3],int)
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
#question 5 answer: 
p=np.ones([2,3],int)
np.vstack([p,2*p])

In [13]:
#question 6: consider the following array s, defined as follows:
s = np.arange(13)**2
#write python code to display the following subset of array s:


array([64, 36, 16,  4,  0])

In [13]:
#question 6: your answer goes here..
s = np.arange(13)**2
s[-5::-2] 

array([64, 36, 16,  4,  0], dtype=int32)

In [ ]:
#question 6 answer: 
s[-5::-2] 

In [15]:
#question 7: consider the following 2-d numpy array, r:
r=np.arange(36) #from 0 to 35
r
r.resize((6,6))
r
#write code to produce the following output from this array r: 


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [16]:
#question 7: your answer goes here..
for i, row in enumerate(r):
    print('row', i, 'is', row)
    for row in r: 
            print(row)

row 0 is [0 1 2 3 4 5]
[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 31 32 33 34 35]
row 1 is [ 6  7  8  9 10 11]
[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 31 32 33 34 35]
row 2 is [12 13 14 15 16 17]
[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 31 32 33 34 35]
row 3 is [18 19 20 21 22 23]
[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 31 32 33 34 35]
row 4 is [24 25 26 27 28 29]
[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 31 32 33 34 35]
row 5 is [30 31 32 33 34 35]
[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 31 32 33 34 35]


In [ ]:
#question 7: answer
for i, row in enumerate(r):
    print('row', i, 'is', row)
    for row in r: 
            print(row)

In [18]:
#for questions 8-10: consider the following array: 
num=np.arange(36)
num
num.resize(6,6)
num




array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [19]:
#question 8: write code to produce every 7th element of the array - from all rows: 


num[:,::7] 



array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [20]:
#question desired output:


array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [20]:
#question 8: your answer goes here..
num[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [ ]:
#question 8: answer
num[:,::7] #all rows, every 7th element

In [21]:
#Question 9: write code to produce the following output from the num array: 
 


array([[14, 16],
       [26, 28]])

In [21]:
#Question 9: your answer goes here..
num[2::2,2::2]

array([[14, 16],
       [26, 28]])

In [ ]:
#Question 9: answer
num[2::2,2::2]

In [23]:
#Question 10: 
#display the following output using one line of code:


array([[0, 1, 2, 3, 4, 5]])

In [22]:
#Question 10: your answer goes here..
num[::7]

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
#Question 10: answer
num[::7] #the first 6 elements of the matrix